### ISSUE TITLE
Upgrade to react-select@2.x.x

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/react-select#5]
Meta-Info | Value
-- | --
ExtProjectId | JCPIM-01.3
Original Estimation | 1h
Remaining Estimation | 0h

### Why?

[grails-text-table](https://github.com/OpusCapita/grails-text-table/pull/36) moved to `react-select@2.x.x`.

I happened because now select dropdown can be rendered using portals.
So there is no more overflow issues. 👍

Therefore we need update our `react-select` package to provide consistent look and feel.

### Known Cons

- `react-select@2.x.x` requires at least `react@16.0.0`
- A lot of API braking changes

### Task

- [x] update `react-select` version to `2.x.x`
- [x] update [SelectDefault.less](https://github.com/OpusCapita/react-select/blob/20bc2ae6d516b55b34d3609afb3f374656c254ab/src/client/components/Select/SelectDefault.less#L1)
- [x] update [SelectCustom.less](https://github.com/OpusCapita/react-select/blob/20bc2ae6d516b55b34d3609afb3f374656c254ab/src/client/components/Select/SelectCustom.less#L1)

**Comment by kvolkovich-sc** [comment]
Issue status: depends on "[dropdown position in portal](https://github.com/OpusCapita/grails-text-table/issues/42)" issue.
Wait for merge and release of https://github.com/JedWatson/react-select/pull/3086 or react-select fork release.

**Comment by estambakio-sc** [comment]
Fixed this until `react-select` updates. Added a custom `MenuPortal` component with proper styling to all selects.

Demo for QA https://opuscapita.github.io/react-select/branches/issue-5-v2/

There in sidebar you can switch between components. If styling breaks after switch - press `F5` on this page.

What to test:
- all components look very opuscapitish (styles part of issue)
- regular input and portalled input look the same (for every component there are 2 inputs for this matter)

**Comment by dshwedovsky-sc** [comment]
React-select components Acync, AsyncCreatable, Creatable, Select checked under FF, IE and Edge
